Make the default resolution appear square to external programs.
Re-enable the PPD check.

diff --git a/src/cups/test-ppds b/src/cups/test-ppds
--- a/src/cups/test-ppds
+++ b/src/cups/test-ppds
@@ -1,56 +1,20 @@
 #!/bin/sh
 
-status=0
-verbose=0
-strict=0
+rm -rf ppd ppd-stamp
 
-usage() {
-    echo "Usage: run-testpattern [-v] [-s]"
-    exit
-}
+make ppd
 
-set_args() {
-    while true ; do
-	case "$1" in
-	    -h*|--h*) usage ;;
-	    -v) verbose=1 ;;
-	    -s) strict=1 ;;
-	    --) shift; args="$@"; return ;;
-	    *) return ;;
-	esac
-    shift
-    done
-}
+ppd_count=`find ppd \( -name '*.ppd.gz' -o -name '*.ppd' \) -print | wc -l`
 
-set_args `getopt vhs "$@"`
+failures="`find ppd -name '*.ppd*' -print | xargs cupstestppd |grep 'FAIL$' | awk -F: '{print $1}'`"
 
-
-if [ -d ppd ] ; then
-    for f in ppd/* ; do
-	echo -n "$f..."
-	cupstestppd -r -q $f/*
-	if [ $? -ne 0 ] ; then
-	    echo -n "FAILED"
-	    if [ $verbose -ne 0 ] ; then
-		cupstestppd $f/* 2>&1 | grep FAIL
-	    fi
-	    status=1
-	else
-	    cupstestppd -q $f/*
-	    if [ $? -ne 0 ] ; then
-		# Don't actually error if strict checks fail.
-		# These errors are less important, and we'll accept them.
-		echo -n "WARNING: strict checks failed"
-		if [ $verbose -ne 0 ] ; then
-		    cupstestppd $f/* 2>&1 | grep FAIL
-		fi
-		if [ $strict -ne 0 ] ; then
-		    status=1
-		fi
-	    fi
-	fi
-	echo
-    done
+if [ -z "$failures" ] ; then
+    echo "All $ppd_count PPD files pass"
+    exit 0
 fi
 
-exit $status
+echo $failures | xargs cupstestppd
+
+fail_count=`echo "$failures" | wc -l`
+echo "$fail_count/$ppd_count fail"
+exit 1
