Fix HP Color LJ 5.
Speed up test-rastertogutenprint by using the lowest resolution possible.

Minor fix to pcl-unprint.

diff --git a/src/cups/test-rastertogutenprint.in b/src/cups/test-rastertogutenprint.in
--- a/src/cups/test-rastertogutenprint.in
+++ b/src/cups/test-rastertogutenprint.in
@@ -47,6 +47,8 @@ md5dir=''
 outdir=''
 cupsargs=''
 postscript=''
+qualarg=''
+use_explicit_quality=1
 npages=3
 jobs=${STP_PARALLEL:-1}
 enable_static='@ENABLE_STATIC@'
@@ -57,6 +59,8 @@ if [ -r "$sdir/../../src/cups/gutenprint-users-manual.pdf" ] ; then
 else
     testfile="$sdir/../../doc/gutenprint-users-manual.pdf"
 fi
+
+quality_presets="FastEconomy Economy Draft Standard High Photo HighPhoto UltraPhoto Best"
 
 usage() {
     echo "Usage: test-rastertogutenprint [options] [PPD files...]"
@@ -74,10 +78,13 @@ usage() {
     echo "    -P        Use PostScript rather than PDF input"
     echo "    -t jobs   Run jobs in parallel (alternatively, use STP_PARALLEL)"
     echo "    -S        Skip simplified PPD files"
+    echo "    -l        Use lowest available quality setting"
+    echo "    -L        Use highest available quality setting"
+    echo "    -X        Don't use explicit quality setting"
     exit 0;
 }
 
-while getopts "hvcgsVnO:m:o:p:St:" opt ; do
+while getopts "hvcgsVnO:m:o:p:St:lLX" opt ; do
     case "$opt" in
 	h*) usage ;;
 	v) valopts='--tool=memcheck' ; valgrind=$((valgrind + 1)) ;;
@@ -93,6 +100,9 @@ while getopts "hvcgsVnO:m:o:p:St:" opt ; do
 	P) postscript=1 ;;
 	t) jobs="$OPTARG" ;;
 	S) skip_simplified=1 ;;
+	X) use_explicit_quality=0 ;;
+	l) use_explicit_quality=1 ;;
+	L) use_explicit_quality=2 ;;
 	\?) usage ;;
 	*) echo "Unknown argument $opt"; usage ;;
     esac
@@ -173,12 +183,12 @@ fi
 
 run_rastertogp() {
     case "$valgrind" in
-	1) valgrind $valopts -q --log-fd=3 --num-callers=50 --leak-check=yes --error-limit=no ./rastertogutenprint.$version 1 1 1 1 "$cupsargs" ;;
-	2) valgrind $valopts --log-fd=3 --num-callers=50 --leak-resolution=high --leak-check=yes --error-limit=no ./rastertogutenprint.$version 1 1 1 1 "$cupsargs" ;;
-	3) valgrind $valopts --log-fd=3 --error-limit=no --num-callers=50 --show-reachable=yes --leak-resolution=high --leak-check=yes ./rastertogutenprint.$version 1 1 1 1 "$cupsargs" ;;
-	4) valgrind $valopts --log-fd=3 ./rastertogutenprint.$version 1 1 1 1 "$cupsargs" ;;
+	1) valgrind $valopts -q --log-fd=3 --num-callers=50 --leak-check=yes --error-limit=no ./rastertogutenprint.$version 1 1 1 1 "$qualarg $cupsargs" ;;
+	2) valgrind $valopts --log-fd=3 --num-callers=50 --leak-resolution=high --leak-check=yes --error-limit=no ./rastertogutenprint.$version 1 1 1 1 "$qualarg $cupsargs" ;;
+	3) valgrind $valopts --log-fd=3 --error-limit=no --num-callers=50 --show-reachable=yes --leak-resolution=high --leak-check=yes ./rastertogutenprint.$version 1 1 1 1 "$qualarg $cupsargs" ;;
+	4) valgrind $valopts --log-fd=3 ./rastertogutenprint.$version 1 1 1 1 "$qualarg $cupsargs" ;;
 	5) cat ;;
-	*) ./rastertogutenprint.$version 1 1 1 1 "$cupsargs" ;;
+	*) ./rastertogutenprint.$version 1 1 1 1 "$qualarg $cupsargs" ;;
     esac
     if [ $? -ne 0 ] ; then
 	retval=1
@@ -245,13 +255,12 @@ get_ppds() {
 
 if [ -n "$make_ppds" -o ! -d ppd/C ] ; then
     rm -rf ppd/C
-    if [ "$skip_simplified" = 1 ] ; then
-        make ppd-nonls
-    else
-        make ppd-nonls-a
-    fi
 ## not all systems can work with gzipped PPDs
-    find ppd/C -name '*.ppd.gz' | xargs gunzip -f
+    if [ "$skip_simplified" = 1 ] ; then
+        EXTRA_GENPPD_OPTS=-Z make ppd-nonls
+    else
+        EXTRA_GENPPD_OPTS=-Z make ppd-nonls-a
+    fi
 fi
 
 do_output() {
@@ -268,7 +277,82 @@ do_output() {
     elif [ -n "$md5dir" ] ; then
 	cat | md5sum | sed "s/-/\*$driver/" > "$md5dir/$driver.md5"
     else
-	cat > /dev/null
+	cat >/dev/null
+    fi
+}
+
+find_resolution() {
+    ppd=$1
+    if [ ! -r "$ppd" ] ; then
+	echo "Can't find $ppd!"
+	exit 1;
+    fi
+    resolutions=`grep "^\\*Resolution " "$ppd" |sed -e 's,/.*,,' -e 's/.* //'`
+    if [ -z "$resolutions" ] ; then
+	return;
+    fi
+    low_resolution=9999999999
+    low_resolution_name=''
+    high_resolution=0
+    high_resolution_name=''
+    for r in $resolutions ; do
+	res=`echo "$r" | sed -e 's/dpi//' -e 's/x/ \\\* /' -e 's/^\([0-9]*\)$/\1 \\\* \1/'`
+	resnum=`eval "expr $res"`
+	if [ "$resnum" -gt $high_resolution ] ; then
+	    high_resolution=$resnum
+	    high_resolution_name=$r
+	fi
+	if [ "$resnum" -lt $low_resolution ] ; then
+	    low_resolution=$resnum
+	    low_resolution_name=$r
+	fi
+    done
+    if [ $use_explicit_quality -eq 1 ] ; then
+	echo "Resolution=$low_resolution_name"
+    elif [ $use_explicit_quality -eq 2 ] ; then
+	echo "Resolution=$high_resolution_name"
+    fi
+}
+
+find_quality_preset() {
+    ppd=$1
+    if [ ! -r "$ppd" ] ; then
+	echo "Can't find $ppd!"
+	exit 1;
+    fi
+    if [ "$use_explicit_quality" -eq 1 ] ; then
+	for q in $quality_presets ; do
+	    if grep -q "^\\*StpQuality $q" "$ppd" ; then
+		echo "StpQuality=$q"
+		return
+	    fi
+	done
+    elif [ "$use_explicit_quality" -eq 2 ] ; then
+	best_quality=''
+	for q in $quality_presets ; do
+	    if grep -q "^\\*StpQuality $q" "$ppd" ; then
+		best_quality=$q
+	    fi
+	done
+	if [ -n "$best_quality" ] ; then
+	    echo "StpQuality=$best_quality"
+	fi
+    fi
+}
+
+find_quality() {
+    ppd=$1
+    if [ ! -r "$ppd" ] ; then
+	echo "Can't find $ppd!"
+	exit 1;
+    fi
+    if [ "$use_explicit_quality" -eq 0 ] ; then
+	return;
+    fi
+    if grep -q '\*Resolution' "$ppd" ; then
+	find_resolution $ppd
+    else
+	find_quality_preset $ppd
     fi
 }
 
@@ -277,18 +361,19 @@ runme() {
     p=$(echo -n "`basename $f |sed -e 's/stp-//' -e 's/@GUTENPRINT_RELEASE_VERSION@.ppd.*$//'`... ")
     PPD=$f
     export PPD
+    qualarg=`find_quality "$f"`
     if [ -x "$cupsdir/cgpdftoraster" ] ; then
 	output="$p `($cupsdir/cgpdftoraster 1 1 1 1 "" < "$tfile" 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
     elif [ -f "$tfile" -a -x "$cupsdir/gstoraster" ] ; then
-	output="$p `($cupsdir/gstoraster 1 1 1 1 \"$cupsargs\" < "$tfile" 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
+	output="$p `($cupsdir/gstoraster 1 1 1 1 \"$qualarg $cupsargs\" < "$tfile" 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
     elif [ -f "$tfile" ] ; then
-	output="$p `($cupsdir/pstops 1 1 1 1 \"$cupsargs\" < "$tfile" 2>/dev/null | $cupsdir/pstoraster 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
+	output="$p `($cupsdir/pstops 1 1 1 1 \"$qualarg $cupsargs\" < "$tfile" 2>/dev/null | $cupsdir/pstoraster 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
     elif [ -x "$cupsdir/pstoraster" ] ; then
-	output="$p `($cupsdir/pdftops 1 1 1 1 \"$cupsargs\" < "$tfile" 2>/dev/null | $cupsdir/pstops 1 1 1 1 \"$pages$cupsargs\" 2>/dev/null | $cupsdir/pstoraster 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
+	output="$p `($cupsdir/pdftops 1 1 1 1 \"$qualarg $cupsargs\" < "$tfile" 2>/dev/null | $cupsdir/pstops 1 1 1 1 \"$pages$qualarg $cupsargs\" 2>/dev/null | $cupsdir/pstoraster 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
     elif [ -x "$cupsdir/gstoraster" ] ; then
-	output="$p `($cupsdir/pdftops 1 1 1 1 \"$cupsargs\" < "$tfile" 2>/dev/null | $cupsdir/gstoraster 1 1 1 1 \"$pages$cupsargs\" 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
+	output="$p `($cupsdir/pdftops 1 1 1 1 \"$qualarg $cupsargs\" < "$tfile" 2>/dev/null | $cupsdir/gstoraster 1 1 1 1 \"$pages$qualarg $cupsargs\" 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2 `"
     else
-	output="$p `($cupsdir/imagetoraster 1 1 1 1 \"$cupsargs\" < calibrate.ppm 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2`"
+	output="$p `($cupsdir/imagetoraster 1 1 1 1 \"$qualarg $cupsargs\" < calibrate.ppm 2>/dev/null | run_rastertogp | do_output) 2>&1 3>&2`"
     fi
     return $?
 }
