Allow test pattern generator to output data to a file.

diff --git a/src/testpattern/run-testpattern b/src/testpattern/run-testpattern
--- a/src/testpattern/run-testpattern
+++ b/src/testpattern/run-testpattern
@@ -16,6 +16,7 @@ valgrind=0
 valopts=''
 extra=''
 dontrun=
+output=''
 
 set_opt() {
     opt=`echo $1 | awk -F= '{print $1}'`
@@ -31,6 +32,7 @@ usage() {
     echo "Usage: run-testpattern [-v|--valgrind]"
     echo "                       [-p|--parameter parameter=value]"
     echo "                       [-n|--dontrun]"
+    echo "                       [-O|--output]"
     echo "                       [--] [printers...]"
     exit 0;
 }
@@ -43,6 +45,7 @@ set_args() {
 	    -c|--cachegrind) valopts='--tool=cachegrind'; valgrind=4 ;;
 	    -g|--gdb-attach) valopts='--gdb-attach=yes' ;;
 	    -p|--parameter) shift; set_opt "$1" ;;
+	    -O|--output) shift; output="$1" ;;
     	    -n|--dontrun) dontrun=1 ;;
 	    --) shift; args="$@"; return ;;
 	    *) return ;;
@@ -116,12 +119,16 @@ EOF
 }
 
 run_testpattern() {
+    suppress=-n
+    if [ -n "$output" ] ; then
+	suppress=''
+    fi
     case "$valgrind" in
-	1) valgrind $valopts -q --num-callers=100 --leak-check=yes ./testpattern -n ;;
-	2) valgrind $valopts --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern -n ;;
-	3) valgrind $valopts --error-limit=no --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern -n ;;
-	4) valgrind $valopts ./testpattern -n ;;
-	*) ./testpattern -n ;;
+	1) valgrind $valopts -q --num-callers=100 --leak-check=yes ./testpattern $suppress ;;
+	2) valgrind $valopts --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern $suppress ;;
+	3) valgrind $valopts --error-limit=no --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern $suppress ;;
+	4) valgrind $valopts ./testpattern $suppress ;;
+	*) ./testpattern $suppress ;;
     esac
     if [ $? -ne 0 ] ; then
 	retval=1
@@ -129,7 +136,7 @@ run_testpattern() {
     exit $retval
 }
 
-set_args `getopt hgvp:nc "$@"`
+set_args `getopt hgvp:ncO: "$@"`
 
 if [ -z "$args" ] ; then
     args=`./printers`
@@ -141,14 +148,25 @@ StandardDithers="EvenTone HybridEvenTone Adaptive Ordered Fast VeryFast Floyd Pr
 
 the_message=''
 
+if [ -z "$dontrun" -a -n "$output" -a ! -d "$output" ] ; then
+    mkdir "$output"
+    if [ "$?" -ne 0 ] ; then
+	echo "Cannot create directory '$output'"
+	exit 1
+    fi
+fi
+
 print_all_testpatterns() {
     if [ -z "`echo $extra |grep DitherAlgorithm`" ] ; then
 	for p in $args ; do
 	    set_message "$p
 "
 	    for d in $StandardDithers ; do
+		if [ -n "$output" ] ; then
+		    outstuff="`printf '\n%s\n' \"output \\\"$output/${p}_${d}\\\";\"`"
+		fi
 		set_message "    $d"
-		print_one_testpattern "$p" "`printf '%s\n' \"parameter \\\"DitherAlgorithm\\\" \\\"$d\\\";\"`" "$extra" "$the_message"
+		print_one_testpattern "$p" "`printf '%s\n' \"parameter \\\"DitherAlgorithm\\\" \\\"$d\\\";\"`" "$extra" "$the_message" "$outstuff"
 		the_message=''
 	    done
 	done
diff --git a/src/testpattern/run-testpattern-1 b/src/testpattern/run-testpattern-1
--- a/src/testpattern/run-testpattern-1
+++ b/src/testpattern/run-testpattern-1
@@ -16,6 +16,7 @@ valgrind=0
 valopts=''
 extra=''
 dontrun=
+output=
 
 set_opt() {
     opt=`echo $1 | awk -F= '{print $1}'`
@@ -31,6 +32,7 @@ usage() {
     echo "Usage: run-testpattern [-v|--valgrind]"
     echo "                       [-p|--parameter parameter=value]"
     echo "                       [-n|--dontrun]"
+    echo "                       [-O|--output]"
     echo "                       [--] [printers...]"
     exit 0;
 }
@@ -46,6 +48,7 @@ set_args() {
 	    -g|--gdb-attach) valopts='--gdb-attach=yes' ;;
 	    -p|--parameter) shift; set_opt "$1" ;;
     	    -n|--dontrun) dontrun=1 ;;
+	    -O|--output) shift; output="$1" ;;
 	    -o|--one) print_command=run_testpattern; dontrun=1 ;;
 	    --) shift; args="$@"; return ;;
 	    *) return ;;
@@ -207,13 +210,16 @@ EOF
 }
 
 run_testpattern() {
+    suppress=-n
+    if [ -n "$output" ] ; then
+	suppress=''
+    fi
     case "$valgrind" in
-	1) valgrind $valopts -q --num-callers=100 --leak-check=yes ./testpattern -n ;;
-	2) valgrind $valopts --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern -n ;;
-	3) valgrind $valopts --error-limit=no --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern -n ;;
-	4) valgrind $valopts ./testpattern -n ;;
-	5) LD_PRELOAD=libefence.so.0.0 ./testpattern -n ;;
-	*) ./testpattern -n ;;
+	1) valgrind $valopts -q --num-callers=100 --leak-check=yes ./testpattern $suppress ;;
+	2) valgrind $valopts --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern $suppress ;;
+	3) valgrind $valopts --error-limit=no --num-callers=100 --show-reachable=yes --leak-resolution=high --leak-check=yes ./testpattern $suppress ;;
+	4) valgrind $valopts ./testpattern $suppress ;;
+	*) ./testpattern $suppress ;;
     esac
     if [ $? -ne 0 ] ; then
 	retval=1
@@ -221,7 +227,7 @@ run_testpattern() {
     exit $retval
 }
 
-set_args `getopt hgvp:nco "$@"`
+set_args `getopt hgvp:ncoO: "$@"`
 
 if [ -z "$args" ] ; then
     args=`./printers`
@@ -242,6 +248,14 @@ RawPrintingModes="Color BW"
 
 the_message=''
 
+if [ -z "$dontrun" -a -n "$output" -a ! -d "$output" ] ; then
+    mkdir "$output"
+    if [ "$?" -ne 0 ] ; then
+	echo "Cannot create directory '$output'"
+	exit 1
+    fi
+fi
+
 print_all_testpatterns() {
     for a in $RawPrintingModes ; do
 	for b in $RawInkTypes ; do
@@ -249,7 +263,10 @@ print_all_testpatterns() {
 		for d in $RawModes ; do
 		    for e in $RawBitDepths ; do
 			set_message "$a $b $c $d $e"
-			print_one_raw_testpattern "raw-data-8" $d $e $b $c $a "$extra" "$the_message" | $print_command
+			if [ -n "$output" ] ; then
+			    outstuff="`printf '\n%s\n' \"output \\\"$output/raw-data-8_${a}_${b}_${c}_${d}_${e}\\\";\"`"
+			fi
+			print_one_raw_testpattern "raw-data-8" $d $e $b $c $a "$extra" "$the_message" "$outstuff"| $print_command
 			the_message=""
 		    done
 		done
@@ -262,7 +279,10 @@ print_all_testpatterns() {
 		for d in $StandardModes ; do
 		    for e in $StandardBitDepths ; do
 			set_message "$a $b $c $d $e"
-			print_one_testpattern "escp2-r800" $d $e $b $c $a "$extra" "$the_message" | $print_command
+			if [ -n "$output" ] ; then
+			    outstuff="`printf '\n%s\n' \"output \\\"$output/escp2-r800_${a}_${b}_${c}_${d}_${e}\\\";\"`"
+			fi
+			print_one_testpattern "escp2-r800" $d $e $b $c $a "$extra" "$the_message" "$outstuff" | $print_command
 			the_message=""
 		    done
 		done
@@ -272,7 +292,10 @@ print_all_testpatterns() {
     for a in $StandardColorCorrections ; do
 	for b in $StandardBitDepths ; do
 	    set_message "Color extended 8 CMYKRB $a $b"
-	    print_one_testpattern "escp2-r800" "extended 8" $b CMYKRB $a Color "$extra" "$the_message" | $print_command
+	    if [ -n "$output" ] ; then
+		outstuff="`printf '\n%s\n' \"output \\\"$output/escp2-r800_${b}_CMYKRB_${a}_Color\\\";\"`"
+	    fi
+	    print_one_testpattern "escp2-r800" "extended 8" $b CMYKRB $a Color "$extra" "$the_message" "$outstuff" | $print_command
 	    the_message=""
 	done
     done
