Update version to 4.3.0-1 Fix lintian ldconfig warning

diff --git a/debian/libgimpprint.postinst b/debian/libgimpprint.postinst
--- a/debian/libgimpprint.postinst
+++ b/debian/libgimpprint.postinst
@@ -22,20 +22,14 @@ set -e
 #     installation fails and the `postinst' is called with `abort-upgrade',
 #     `abort-remove' or `abort-deconfigure'.
 
-case "$1" in
-    configure)
-      ldconfig
-    ;;
+#s/^if\s+\[\s+"\$1"\s+=\s+"configure"\s+\];\s+then\s+ldconfig\b//m;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
-
-    ;;
-
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 0
-    ;;
-esac
+if [ "$1" = "configure" ]; then ldconfig
+elif [ "$1" = "abort-upgrade" -o "$1" = "abort-remove" -o "$1" = "abort-deconfigure" ] ; then :
+else
+  echo "postinst called with unknown argument \`$1'" >&2
+  exit 0
+fi
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
